// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gate.proto

package gate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GateMsgType int32

const (
	GateMsgType_gs GateMsgType = 1
	GateMsgType_us GateMsgType = 2
)

var GateMsgType_name = map[int32]string{
	1: "gs",
	2: "us",
}

var GateMsgType_value = map[string]int32{
	"gs": 1,
	"us": 2,
}

func (x GateMsgType) Enum() *GateMsgType {
	p := new(GateMsgType)
	*p = x
	return p
}

func (x GateMsgType) String() string {
	return proto.EnumName(GateMsgType_name, int32(x))
}

func (x *GateMsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GateMsgType_value, data, "GateMsgType")
	if err != nil {
		return err
	}
	*x = GateMsgType(value)
	return nil
}

func (GateMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{0}
}

type Msg int32

const (
	// 注册服务
	Msg_registerServerReq  Msg = 1
	Msg_registerServerResp Msg = 2
	Msg_ping               Msg = 3
	Msg_pong               Msg = 4
	Msg_userLostConnection Msg = 5
)

var Msg_name = map[int32]string{
	1: "registerServerReq",
	2: "registerServerResp",
	3: "ping",
	4: "pong",
	5: "userLostConnection",
}

var Msg_value = map[string]int32{
	"registerServerReq":  1,
	"registerServerResp": 2,
	"ping":               3,
	"pong":               4,
	"userLostConnection": 5,
}

func (x Msg) Enum() *Msg {
	p := new(Msg)
	*p = x
	return p
}

func (x Msg) String() string {
	return proto.EnumName(Msg_name, int32(x))
}

func (x *Msg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Msg_value, data, "Msg")
	if err != nil {
		return err
	}
	*x = Msg(value)
	return nil
}

func (Msg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{1}
}

type ErrorCode int32

const (
	ErrorCode_success ErrorCode = 0
	ErrorCode_failed  ErrorCode = 1
)

var ErrorCode_name = map[int32]string{
	0: "success",
	1: "failed",
}

var ErrorCode_value = map[string]int32{
	"success": 0,
	"failed":  1,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{2}
}

type ServerType int32

const (
	ServerType_service ServerType = 0
	ServerType_game    ServerType = 1
)

var ServerType_name = map[int32]string{
	0: "service",
	1: "game",
}

var ServerType_value = map[string]int32{
	"service": 0,
	"game":    1,
}

func (x ServerType) Enum() *ServerType {
	p := new(ServerType)
	*p = x
	return p
}

func (x ServerType) String() string {
	return proto.EnumName(ServerType_name, int32(x))
}

func (x *ServerType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerType_value, data, "ServerType")
	if err != nil {
		return err
	}
	*x = ServerType(value)
	return nil
}

func (ServerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{3}
}

type GateMsg struct {
	Gmt                  *GateMsgType `protobuf:"varint,1,opt,name=gmt,enum=gate.GateMsgType" json:"gmt,omitempty"`
	ConnId               *uint64      `protobuf:"varint,2,opt,name=conn_id,json=connId" json:"conn_id,omitempty"`
	MsgType              *uint32      `protobuf:"varint,3,opt,name=msg_type,json=msgType" json:"msg_type,omitempty"`
	MsgId                *uint32      `protobuf:"varint,4,opt,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	Data                 []byte       `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GateMsg) Reset()         { *m = GateMsg{} }
func (m *GateMsg) String() string { return proto.CompactTextString(m) }
func (*GateMsg) ProtoMessage()    {}
func (*GateMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{0}
}

func (m *GateMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateMsg.Unmarshal(m, b)
}
func (m *GateMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateMsg.Marshal(b, m, deterministic)
}
func (m *GateMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateMsg.Merge(m, src)
}
func (m *GateMsg) XXX_Size() int {
	return xxx_messageInfo_GateMsg.Size(m)
}
func (m *GateMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GateMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GateMsg proto.InternalMessageInfo

func (m *GateMsg) GetGmt() GateMsgType {
	if m != nil && m.Gmt != nil {
		return *m.Gmt
	}
	return GateMsgType_gs
}

func (m *GateMsg) GetConnId() uint64 {
	if m != nil && m.ConnId != nil {
		return *m.ConnId
	}
	return 0
}

func (m *GateMsg) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *GateMsg) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *GateMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RespTips struct {
	Code                 *ErrorCode `protobuf:"varint,1,opt,name=code,enum=gate.ErrorCode" json:"code,omitempty"`
	Msg                  *string    `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RespTips) Reset()         { *m = RespTips{} }
func (m *RespTips) String() string { return proto.CompactTextString(m) }
func (*RespTips) ProtoMessage()    {}
func (*RespTips) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{1}
}

func (m *RespTips) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespTips.Unmarshal(m, b)
}
func (m *RespTips) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespTips.Marshal(b, m, deterministic)
}
func (m *RespTips) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespTips.Merge(m, src)
}
func (m *RespTips) XXX_Size() int {
	return xxx_messageInfo_RespTips.Size(m)
}
func (m *RespTips) XXX_DiscardUnknown() {
	xxx_messageInfo_RespTips.DiscardUnknown(m)
}

var xxx_messageInfo_RespTips proto.InternalMessageInfo

func (m *RespTips) GetCode() ErrorCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ErrorCode_success
}

func (m *RespTips) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type RegisterServerReq struct {
	ServerType           *ServerType `protobuf:"varint,1,opt,name=server_type,json=serverType,enum=gate.ServerType" json:"server_type,omitempty"`
	MsgType              *uint32     `protobuf:"varint,2,opt,name=msg_type,json=msgType" json:"msg_type,omitempty"`
	ServerId             *uint32     `protobuf:"varint,3,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegisterServerReq) Reset()         { *m = RegisterServerReq{} }
func (m *RegisterServerReq) String() string { return proto.CompactTextString(m) }
func (*RegisterServerReq) ProtoMessage()    {}
func (*RegisterServerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{2}
}

func (m *RegisterServerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServerReq.Unmarshal(m, b)
}
func (m *RegisterServerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServerReq.Marshal(b, m, deterministic)
}
func (m *RegisterServerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServerReq.Merge(m, src)
}
func (m *RegisterServerReq) XXX_Size() int {
	return xxx_messageInfo_RegisterServerReq.Size(m)
}
func (m *RegisterServerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServerReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServerReq proto.InternalMessageInfo

func (m *RegisterServerReq) GetServerType() ServerType {
	if m != nil && m.ServerType != nil {
		return *m.ServerType
	}
	return ServerType_service
}

func (m *RegisterServerReq) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *RegisterServerReq) GetServerId() uint32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

type RegisterServerResp struct {
	ServerType           *ServerType `protobuf:"varint,1,opt,name=server_type,json=serverType,enum=gate.ServerType" json:"server_type,omitempty"`
	MsgType              *uint32     `protobuf:"varint,2,opt,name=msg_type,json=msgType" json:"msg_type,omitempty"`
	ServerId             *uint32     `protobuf:"varint,3,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	ServerTime           *int64      `protobuf:"varint,4,opt,name=server_time,json=serverTime" json:"server_time,omitempty"`
	Ret                  *RespTips   `protobuf:"bytes,5,opt,name=ret" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegisterServerResp) Reset()         { *m = RegisterServerResp{} }
func (m *RegisterServerResp) String() string { return proto.CompactTextString(m) }
func (*RegisterServerResp) ProtoMessage()    {}
func (*RegisterServerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{3}
}

func (m *RegisterServerResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServerResp.Unmarshal(m, b)
}
func (m *RegisterServerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServerResp.Marshal(b, m, deterministic)
}
func (m *RegisterServerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServerResp.Merge(m, src)
}
func (m *RegisterServerResp) XXX_Size() int {
	return xxx_messageInfo_RegisterServerResp.Size(m)
}
func (m *RegisterServerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServerResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServerResp proto.InternalMessageInfo

func (m *RegisterServerResp) GetServerType() ServerType {
	if m != nil && m.ServerType != nil {
		return *m.ServerType
	}
	return ServerType_service
}

func (m *RegisterServerResp) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *RegisterServerResp) GetServerId() uint32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *RegisterServerResp) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *RegisterServerResp) GetRet() *RespTips {
	if m != nil {
		return m.Ret
	}
	return nil
}

type Ping struct {
	S                    *int64   `protobuf:"varint,1,opt,name=s" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{4}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetS() int64 {
	if m != nil && m.S != nil {
		return *m.S
	}
	return 0
}

type Pong struct {
	S                    *int64   `protobuf:"varint,1,opt,name=s" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{5}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetS() int64 {
	if m != nil && m.S != nil {
		return *m.S
	}
	return 0
}

type S2GUserMsg struct {
	ConnIds              []uint64 `protobuf:"varint,1,rep,name=conn_ids,json=connIds" json:"conn_ids,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2GUserMsg) Reset()         { *m = S2GUserMsg{} }
func (m *S2GUserMsg) String() string { return proto.CompactTextString(m) }
func (*S2GUserMsg) ProtoMessage()    {}
func (*S2GUserMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{6}
}

func (m *S2GUserMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2GUserMsg.Unmarshal(m, b)
}
func (m *S2GUserMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2GUserMsg.Marshal(b, m, deterministic)
}
func (m *S2GUserMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2GUserMsg.Merge(m, src)
}
func (m *S2GUserMsg) XXX_Size() int {
	return xxx_messageInfo_S2GUserMsg.Size(m)
}
func (m *S2GUserMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_S2GUserMsg.DiscardUnknown(m)
}

var xxx_messageInfo_S2GUserMsg proto.InternalMessageInfo

func (m *S2GUserMsg) GetConnIds() []uint64 {
	if m != nil {
		return m.ConnIds
	}
	return nil
}

func (m *S2GUserMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserLostConnectionMsg struct {
	ConnId               *uint64  `protobuf:"varint,1,opt,name=conn_id,json=connId" json:"conn_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLostConnectionMsg) Reset()         { *m = UserLostConnectionMsg{} }
func (m *UserLostConnectionMsg) String() string { return proto.CompactTextString(m) }
func (*UserLostConnectionMsg) ProtoMessage()    {}
func (*UserLostConnectionMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{7}
}

func (m *UserLostConnectionMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLostConnectionMsg.Unmarshal(m, b)
}
func (m *UserLostConnectionMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLostConnectionMsg.Marshal(b, m, deterministic)
}
func (m *UserLostConnectionMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLostConnectionMsg.Merge(m, src)
}
func (m *UserLostConnectionMsg) XXX_Size() int {
	return xxx_messageInfo_UserLostConnectionMsg.Size(m)
}
func (m *UserLostConnectionMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLostConnectionMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UserLostConnectionMsg proto.InternalMessageInfo

func (m *UserLostConnectionMsg) GetConnId() uint64 {
	if m != nil && m.ConnId != nil {
		return *m.ConnId
	}
	return 0
}

type UserMsg struct {
	MsgType              *uint32  `protobuf:"varint,1,opt,name=msg_type,json=msgType" json:"msg_type,omitempty"`
	MsgId                *uint32  `protobuf:"varint,2,opt,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMsg) Reset()         { *m = UserMsg{} }
func (m *UserMsg) String() string { return proto.CompactTextString(m) }
func (*UserMsg) ProtoMessage()    {}
func (*UserMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{8}
}

func (m *UserMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMsg.Unmarshal(m, b)
}
func (m *UserMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMsg.Marshal(b, m, deterministic)
}
func (m *UserMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMsg.Merge(m, src)
}
func (m *UserMsg) XXX_Size() int {
	return xxx_messageInfo_UserMsg.Size(m)
}
func (m *UserMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UserMsg proto.InternalMessageInfo

func (m *UserMsg) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *UserMsg) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *UserMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("gate.GateMsgType", GateMsgType_name, GateMsgType_value)
	proto.RegisterEnum("gate.Msg", Msg_name, Msg_value)
	proto.RegisterEnum("gate.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("gate.ServerType", ServerType_name, ServerType_value)
	proto.RegisterType((*GateMsg)(nil), "gate.GateMsg")
	proto.RegisterType((*RespTips)(nil), "gate.RespTips")
	proto.RegisterType((*RegisterServerReq)(nil), "gate.RegisterServerReq")
	proto.RegisterType((*RegisterServerResp)(nil), "gate.RegisterServerResp")
	proto.RegisterType((*Ping)(nil), "gate.Ping")
	proto.RegisterType((*Pong)(nil), "gate.Pong")
	proto.RegisterType((*S2GUserMsg)(nil), "gate.S2GUserMsg")
	proto.RegisterType((*UserLostConnectionMsg)(nil), "gate.UserLostConnectionMsg")
	proto.RegisterType((*UserMsg)(nil), "gate.UserMsg")
}

func init() { proto.RegisterFile("gate.proto", fileDescriptor_743bb58a714d8b7d) }

var fileDescriptor_743bb58a714d8b7d = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0xe7, 0x24, 0x6d, 0xda, 0xeb, 0x18, 0xae, 0x45, 0xa1, 0x13, 0x42, 0x54, 0x29, 0x0f,
	0x55, 0x1f, 0x26, 0xe8, 0x2b, 0x4f, 0x68, 0x42, 0x53, 0x25, 0x10, 0xc8, 0x1b, 0xcf, 0x23, 0x4a,
	0x0e, 0xcb, 0x12, 0x89, 0x83, 0xcf, 0x9d, 0xb4, 0x17, 0xbe, 0x01, 0x5f, 0x8a, 0x4f, 0x86, 0xec,
	0x94, 0x36, 0x5b, 0xe1, 0x75, 0x4f, 0xb9, 0xf8, 0x7f, 0xbe, 0xfb, 0xdf, 0xf9, 0x07, 0xa0, 0x72,
	0x87, 0x67, 0x8d, 0x35, 0xce, 0x88, 0xc4, 0xc7, 0xd9, 0x2f, 0x06, 0xe9, 0x45, 0xee, 0xf0, 0x23,
	0x29, 0x31, 0x87, 0x58, 0x55, 0x6e, 0xca, 0x66, 0x6c, 0x71, 0xb2, 0x1a, 0x9f, 0x85, 0xdc, 0xad,
	0x76, 0x75, 0xdb, 0xa0, 0xf4, 0xaa, 0x78, 0x06, 0x69, 0x61, 0xea, 0xfa, 0x5a, 0x97, 0xd3, 0x68,
	0xc6, 0x16, 0x89, 0xec, 0xfb, 0xdf, 0x75, 0x29, 0x4e, 0x61, 0x50, 0x91, 0xba, 0x76, 0xb7, 0x0d,
	0x4e, 0xe3, 0x19, 0x5b, 0x3c, 0x92, 0x69, 0xd5, 0x5e, 0x14, 0x13, 0xe8, 0x7b, 0x49, 0x97, 0xd3,
	0x24, 0x08, 0xbd, 0x8a, 0xd4, 0xba, 0x14, 0x02, 0x92, 0x32, 0x77, 0xf9, 0xb4, 0x37, 0x63, 0x8b,
	0x63, 0x19, 0xe2, 0xec, 0x1d, 0x0c, 0x24, 0x52, 0x73, 0xa5, 0x1b, 0x12, 0x73, 0x48, 0x0a, 0x53,
	0xe2, 0xd6, 0xd0, 0xe3, 0xd6, 0xd0, 0x7b, 0x6b, 0x8d, 0x3d, 0x37, 0x25, 0xca, 0x20, 0x0a, 0x0e,
	0x71, 0x45, 0x2a, 0x78, 0x19, 0x4a, 0x1f, 0x66, 0x3f, 0x61, 0x2c, 0x51, 0x69, 0x72, 0x68, 0x2f,
	0xd1, 0xde, 0xa0, 0x95, 0xf8, 0x43, 0xbc, 0x81, 0x11, 0x85, 0x9f, 0xd6, 0x60, 0x5b, 0x92, 0xb7,
	0x25, 0xdb, 0xac, 0x30, 0x22, 0xd0, 0x2e, 0xbe, 0x33, 0x50, 0x74, 0x77, 0xa0, 0xe7, 0x30, 0xdc,
	0x56, 0xd3, 0xe5, 0x76, 0xd8, 0x41, 0x7b, 0xb0, 0x2e, 0xb3, 0xdf, 0x0c, 0xc4, 0x7d, 0x03, 0xd4,
	0x3c, 0xa0, 0x03, 0xf1, 0x72, 0xdf, 0x4a, 0x57, 0x18, 0x96, 0x1e, 0xef, 0x0a, 0xeb, 0x0a, 0xc5,
	0x0c, 0x62, 0x8b, 0x2e, 0x2c, 0x7e, 0xb4, 0x3a, 0x69, 0x3d, 0xfc, 0x5d, 0xbb, 0xf4, 0x52, 0xf6,
	0x04, 0x92, 0xcf, 0xba, 0x56, 0xe2, 0x18, 0x18, 0x05, 0xaf, 0xb1, 0x64, 0x14, 0x4e, 0xcd, 0xc1,
	0xe9, 0x5b, 0x80, 0xcb, 0xd5, 0xc5, 0x17, 0x42, 0xeb, 0x29, 0x3a, 0x85, 0xc1, 0x16, 0x10, 0x9f,
	0x12, 0x2f, 0x12, 0x99, 0xb6, 0x84, 0xd0, 0xee, 0xc1, 0xa3, 0xce, 0x83, 0xbf, 0x86, 0x89, 0xbf,
	0xf9, 0xc1, 0x90, 0x3b, 0x37, 0x75, 0x8d, 0x85, 0xd3, 0xa6, 0xf6, 0x75, 0x3a, 0xa0, 0xb1, 0x2e,
	0x68, 0xd9, 0x27, 0x48, 0x3b, 0xbd, 0x76, 0x0b, 0x62, 0xff, 0x63, 0x2e, 0xfa, 0x17, 0x73, 0xf1,
	0xde, 0xc2, 0xf2, 0x05, 0x8c, 0x3a, 0x98, 0x8b, 0x3e, 0x44, 0x8a, 0x38, 0xf3, 0xdf, 0x0d, 0xf1,
	0x68, 0xf9, 0x15, 0x62, 0xdf, 0x6b, 0x02, 0x63, 0x7b, 0x1f, 0x2b, 0xce, 0xc4, 0x53, 0x10, 0xf6,
	0xe0, 0xb1, 0x79, 0x24, 0x06, 0x90, 0x34, 0xba, 0x56, 0x3c, 0x0e, 0x91, 0xa9, 0x15, 0x4f, 0x7c,
	0xee, 0xe6, 0x60, 0x56, 0xde, 0x5b, 0xbe, 0x82, 0xe1, 0x0e, 0x6b, 0x31, 0x82, 0x94, 0x36, 0x45,
	0x81, 0x44, 0xfc, 0x48, 0x00, 0xf4, 0xbf, 0xe5, 0xfa, 0x3b, 0x96, 0x9c, 0x2d, 0xe7, 0x00, 0x7b,
	0x4e, 0x42, 0x1a, 0xda, 0x1b, 0x5d, 0x20, 0x3f, 0xf2, 0x2d, 0x54, 0x5e, 0x21, 0x67, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xeb, 0xcf, 0xb0, 0x7b, 0xe2, 0x03, 0x00, 0x00,
}
