// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg int32

const (
	Msg_login Msg = 1
)

var Msg_name = map[int32]string{
	1: "login",
}

var Msg_value = map[string]int32{
	"login": 1,
}

func (x Msg) Enum() *Msg {
	p := new(Msg)
	*p = x
	return p
}

func (x Msg) String() string {
	return proto.EnumName(Msg_name, int32(x))
}

func (x *Msg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Msg_value, data, "Msg")
	if err != nil {
		return err
	}
	*x = Msg(value)
	return nil
}

func (Msg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

type DeviceInfo struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *DeviceInfo) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type LoginRequest struct {
	//登录的类型标识
	LoginType *string `protobuf:"bytes,1,opt,name=login_type,json=loginType" json:"login_type,omitempty"`
	//登录游戏标识
	AppId *string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	//登录用户名
	UserName *string `protobuf:"bytes,3,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	//登录密码
	Password *string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	//用户第三方登录provider
	Provider *string `protobuf:"bytes,5,opt,name=provider" json:"provider,omitempty"`
	// device id
	DeviceId *string `protobuf:"bytes,6,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	//登录设备信息列表
	DInfos []*DeviceInfo `protobuf:"bytes,7,rep,name=dInfos" json:"dInfos,omitempty"`
	//Connection type: tcp, ws(web socket)...
	//(default tcp)
	Protocol             *string  `protobuf:"bytes,8,opt,name=protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLoginType() string {
	if m != nil && m.LoginType != nil {
		return *m.LoginType
	}
	return ""
}

func (m *LoginRequest) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *LoginRequest) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *LoginRequest) GetProvider() string {
	if m != nil && m.Provider != nil {
		return *m.Provider
	}
	return ""
}

func (m *LoginRequest) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *LoginRequest) GetDInfos() []*DeviceInfo {
	if m != nil {
		return m.DInfos
	}
	return nil
}

func (m *LoginRequest) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

type LoginResponse struct {
	//登录状态返回值
	Ret *int32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	//用户的id
	Uid *uint64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	//用户的token
	Token *string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	//绑定手机号
	BindPhone *string `protobuf:"bytes,4,opt,name=bind_phone,json=bindPhone" json:"bind_phone,omitempty"`
	//游戏服的ip和端口
	Ips                  []string `protobuf:"bytes,5,rep,name=ips" json:"ips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *LoginResponse) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *LoginResponse) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *LoginResponse) GetBindPhone() string {
	if m != nil && m.BindPhone != nil {
		return *m.BindPhone
	}
	return ""
}

func (m *LoginResponse) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

func init() {
	proto.RegisterEnum("account.Msg", Msg_name, Msg_value)
	proto.RegisterType((*DeviceInfo)(nil), "account.DeviceInfo")
	proto.RegisterType((*LoginRequest)(nil), "account.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "account.LoginResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xe9, 0xbf, 0xeb, 0xb6, 0xde, 0xbf, 0x83, 0x11, 0x15, 0x82, 0x22, 0x8c, 0x3d, 0x0d,
	0x85, 0x3d, 0x88, 0x1f, 0xc1, 0x97, 0x81, 0x8a, 0x14, 0xdf, 0x4b, 0x6c, 0xae, 0x33, 0x6c, 0x4b,
	0xae, 0x4d, 0x3a, 0x99, 0x5f, 0x5e, 0xb9, 0x69, 0xa6, 0x6f, 0xf7, 0x9c, 0xd3, 0xde, 0xcb, 0xf9,
	0x05, 0x26, 0xaa, 0x69, 0x5c, 0x67, 0xc3, 0x92, 0x5a, 0x17, 0x9c, 0x18, 0x25, 0x39, 0xbf, 0x03,
	0xb8, 0xc7, 0xbd, 0x69, 0x70, 0x65, 0xdf, 0x9c, 0x98, 0x42, 0xbe, 0xc1, 0x83, 0xcc, 0x66, 0xd9,
	0xa2, 0xac, 0x78, 0x14, 0x67, 0x50, 0xec, 0xd5, 0xb6, 0x43, 0xf9, 0x2f, 0x7a, 0xbd, 0x98, 0x7f,
	0x67, 0x70, 0xf2, 0xe0, 0xd6, 0xc6, 0x56, 0xf8, 0xd1, 0xa1, 0x0f, 0xe2, 0x0a, 0x60, 0xcb, 0xba,
	0x0e, 0x07, 0xc2, 0xf4, 0x7f, 0x19, 0x9d, 0x97, 0x03, 0xa1, 0x38, 0x87, 0xa1, 0x22, 0xaa, 0x8d,
	0x3e, 0xae, 0x51, 0x44, 0x2b, 0x2d, 0x2e, 0xa1, 0xec, 0x3c, 0xb6, 0xb5, 0x55, 0x3b, 0x94, 0x79,
	0x4c, 0xc6, 0x6c, 0x3c, 0xa9, 0x1d, 0x8a, 0x0b, 0x18, 0x93, 0xf2, 0xfe, 0xd3, 0xb5, 0x5a, 0x0e,
	0xfa, 0xec, 0xa8, 0x63, 0xd6, 0xba, 0xbd, 0xd1, 0xd8, 0xca, 0x22, 0x65, 0x49, 0xf3, 0x52, 0x1d,
	0x1b, 0xf1, 0xb9, 0x61, 0x1f, 0xf6, 0xc6, 0x4a, 0x8b, 0x1b, 0x18, 0x6a, 0x6e, 0xea, 0xe5, 0x68,
	0x96, 0x2f, 0xfe, 0xdf, 0x9e, 0x2e, 0x8f, 0x5c, 0xfe, 0x28, 0x54, 0xe9, 0x93, 0x74, 0x25, 0xb8,
	0xc6, 0x6d, 0xe5, 0xf8, 0xf7, 0x4a, 0xd4, 0xf3, 0x2f, 0x98, 0x24, 0x00, 0x9e, 0x9c, 0xf5, 0xc8,
	0xe8, 0x5a, 0x0c, 0xb1, 0x7a, 0x51, 0xf1, 0xc8, 0x4e, 0x97, 0x1a, 0x0f, 0x2a, 0x1e, 0x19, 0x66,
	0x70, 0x1b, 0xb4, 0xa9, 0x6b, 0x2f, 0x98, 0xdd, 0xab, 0xb1, 0xba, 0xa6, 0x77, 0x67, 0x31, 0x55,
	0x2d, 0xd9, 0x79, 0x66, 0x83, 0xd7, 0x18, 0xf2, 0xb2, 0x98, 0xe5, 0xfc, 0x26, 0x86, 0xfc, 0xf5,
	0x14, 0xf2, 0x47, 0xbf, 0x16, 0x25, 0x14, 0x91, 0xf0, 0x34, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x0f, 0xf2, 0x9f, 0x81, 0xde, 0x01, 0x00, 0x00,
}
