// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hall.proto

package hall

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg int32

const (
	Msg_login Msg = 1
)

var Msg_name = map[int32]string{
	1: "login",
}

var Msg_value = map[string]int32{
	"login": 1,
}

func (x Msg) Enum() *Msg {
	p := new(Msg)
	*p = x
	return p
}

func (x Msg) String() string {
	return proto.EnumName(Msg_name, int32(x))
}

func (x *Msg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Msg_value, data, "Msg")
	if err != nil {
		return err
	}
	*x = Msg(value)
	return nil
}

func (Msg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{0}
}

type LoginReq struct {
	Uid                  *uint64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Token                *string  `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *LoginReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("hall.Msg", Msg_name, Msg_value)
	proto.RegisterType((*LoginReq)(nil), "hall.LoginReq")
}

func init() { proto.RegisterFile("hall.proto", fileDescriptor_4e141f6d4a8804e5) }

var fileDescriptor_4e141f6d4a8804e5 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x48, 0xcc, 0xc9,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x8c, 0xb8, 0x38, 0x7c, 0xf2,
	0xd3, 0x33, 0xf3, 0x82, 0x52, 0x0b, 0x85, 0x04, 0xb8, 0x98, 0x4b, 0x33, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x58, 0x82, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xfc, 0xec, 0xd4, 0x3c, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x4b, 0x80, 0x8b, 0xd9, 0xb7, 0x38, 0x5d, 0x88,
	0x93, 0x8b, 0x35, 0x07, 0xa4, 0x55, 0x80, 0x11, 0x10, 0x00, 0x00, 0xff, 0xff, 0xca, 0x6f, 0xe3,
	0xf3, 0x58, 0x00, 0x00, 0x00,
}
